apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/axel7083/boycott/backend:next
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              hostPort: 8888
          envFrom:
            # postgres DB & USER & PASSWORD
            - secretRef:
                name: db-secret-credentials
            # minio USER & PASSWORD
            - secretRef:
                name: minio-secret-credentials
          env:
            - name: POSTGRES_HOST
              value: "postgresdb"
            - name: MINIO_HOST
              value: "minio"
            - name: RESTRICT_HOSTS
              value: "true"
            - name: TRUSTED_HOSTS
              value: "stefanini.dev"